export const en = {
  locale: "en",
  siteName: "Atomy HemoHIM",
  whatsapp: "+7 708 271 7008",
  whatsappLink: "https://wa.me/77082717008",
  nav: { product: "Product", ingredients: "Ingredients", benefits: "Benefits", atomy: "Atomy", catalog: "Catalog", registration: "Registration", reviews: "Reviews", order: "Order", faq: "FAQ" },
  common: { koreanProduct: "A Korean Atomy product", productLabel: "Product", ingredientsLabel: "Ingredients", benefitsLabel: "Benefits", videoLabel: "Video", galleryLabel: "Gallery", formatLabel: "Format", orderLabel: "Ordering", contactsLabel: "Contact us", languageLabel: "Language", consultation: "Get a consultation", watchVideo: "Watch the video" },
  hero: { title: "Atomy HemoHIM", description: "A premium Korean product featuring a carefully developed botanical complex of Angelica Gigas, Cnidium Officinale and Paeonia Lactiflora.", cta: "Message us on WhatsApp", secondary: "Discover HemoHIM", imageAlt: "Atomy HemoHIM product packaging", stats: [{ value: "3", label: "botanical ingredients" }, { value: "20 ml", label: "per sachet" }, { value: "60", label: "sachets per box" }] },
  productIntro: {
    title: "HemoHIM — a product known for the experience behind it",
    paragraphs: [
      "Why do some people feel completely drained by evening while others still have energy after a demanding day? Well-being is shaped by many factors, including sleep, nutrition, stress, physical activity and the normal functioning of the immune system.",
      "HemoHIM has remained one of Atomy’s most recognizable products for many years. Its botanical complex was developed through a multi-year research project at the Korea Atomic Energy Research Institute (KAERI), and the product is manufactured by Kolmar BNH.",
      "The complex is built around three botanicals: giant angelica, cnidium root and peony. Modern extraction and standardization methods made it possible to create a consistent botanical composition that became the foundation of HemoHIM.",
      "Across many markets, HemoHIM is chosen by people with active lifestyles, particularly during periods of increased physical and emotional demand, intensive work and frequent travel.",
      "HemoHIM is not a medicine and is not intended to treat disease. It is a dietary supplement used as part of a balanced diet and healthy lifestyle.",
      "What makes HemoHIM notable is the structured approach behind its development: years of research, modern manufacturing and a strong focus on quality control.",
      "New supplements appear every day, yet relatively few remain internationally recognized for years. HemoHIM continues to be one of Atomy’s flagship products."
    ],
    note: "HemoHIM is a dietary supplement, not a medicine. If you have a medical condition, are pregnant or breastfeeding, have allergies, or take medication, consult a qualified healthcare professional before use.",
    imageAlt: "Atomy HemoHIM in convenient single-serve sachets", imageBadge: "Convenient format", imageTitle: "20 ml single-serve sachets", imageText: "60 sachets in each box"
  },
  ingredients: { title: "Three botanical ingredients", text: "The distinctive HemoHIM complex combines three carefully selected botanical ingredients.", items: [{ title: "Giant angelica", description: "Korean angelica, one of the three botanicals at the heart of the HemoHIM complex.", imageAlt: "Giant angelica used in the HemoHIM botanical complex" }, { title: "Cnidium root", description: "A traditional botanical ingredient selected as part of HemoHIM’s proprietary blend.", imageAlt: "Cnidium root used in the HemoHIM botanical complex" }, { title: "Japanese peony", description: "Peony completing the balanced three-botanical formula.", imageAlt: "Japanese peony used in the HemoHIM botanical complex" }] },
  benefits: { title: "Why choose HemoHIM", items: [{ title: "Developed in Korea", text: "A product rooted in Korean research and botanical expertise." }, { title: "Convenient sachets", text: "Easy to store, carry and include in your everyday routine." }, { title: "International recognition", text: "One of Atomy’s best-known products across international markets." }, { title: "Quality-focused philosophy", text: "Aligned with Atomy’s principle of exceptional quality at a reasonable price." }] },
  video: { title: "The HemoHIM story and development", description: "Watch the presentation to learn about the botanical complex, its development background and the key ideas behind HemoHIM.", eyebrow: "Product video", cardTitle: "What you will learn", points: ["How HemoHIM was developed", "What makes up the botanical complex", "The approach to development and quality"], button: "Ask a question on WhatsApp", iframeTitle: "Atomy HemoHIM presentation video" },
  gallery: { title: "HemoHIM up close", description: "Official product images showing the box, individual packaging and convenient sachet format.", images: ["Atomy HemoHIM official product image", "Atomy HemoHIM packaging", "Atomy HemoHIM sachets"], formatTitle: "Convenient single-serve sachets for everyday use", formatText: "The compact sachets are easy to store at home or take with you. Pack size and directions for use may vary by market; always refer to the information on your local packaging." },
  aboutAtomy: { label: "Atomy", title: "About Atomy", text: "Atomy is a South Korean consumer company founded in 2009. It offers products across health, beauty, personal care, home care and everyday living, guided by its philosophy of delivering exceptional quality at a reasonable price." },
  catalog: { label: "Atomy catalog", title: "Explore the full Atomy range", description: "The catalog includes products for health, skincare, personal care, the home and everyday living. For current availability and pricing, the official Atomy Kazakhstan online store is the best source.", allProducts: "View all products", printCatalog: "Atomy Catalog 2026", categoriesLabel: "Catalog categories", categories: ["Health", "Skincare", "Children", "Men", "Sun protection", "Makeup", "Hair & body", "Oral care", "Food", "Lifestyle products"], note: "Prices, availability and assortment may change. Please check the official Atomy Kazakhstan website before ordering." },
  registration: { label: "Partnership", title: "Register with Atomy online", description: "Registration is completed on the official Atomy Kazakhstan website using the personal registration link. If you need help with the form or any step of the process, message us on WhatsApp.", button: "Start registration", helpButton: "Get help on WhatsApp", steps: ["Open the official registration page.", "Enter your details and follow Atomy’s instructions.", "If you need assistance, contact us on WhatsApp."] },
  reviews: { label: "Reviews", title: "Personal experiences with HemoHIM", description: "This section features individual stories and personal impressions from people who have used the product.", iframeTitle: "HemoHIM customer review video", cardLabel: "Video review", cardTitle: "A personal experience", cardText: "Watch one person’s account of their experience with HemoHIM. Personal stories can provide useful context, but they do not replace medical advice and do not guarantee similar results for others.", disclaimer: "Individual experiences vary. This review is not medical advice and does not prove a therapeutic effect." },
  order: { title: "How to order HemoHIM", steps: ["Message us on WhatsApp.", "Confirm availability, current price and delivery options.", "Receive clear product information and answers to your questions.", "Place your order using the most convenient option."], cta: "Order via WhatsApp" },
  faq: { title: "Frequently asked questions", items: [{ question: "What is HemoHIM?", answer: "HemoHIM is an Atomy botanical product based on a complex of giant angelica, cnidium root and peony." }, { question: "Is HemoHIM a medicine?", answer: "No. HemoHIM is not a medicine. The information on this website is provided for general informational purposes only." }, { question: "How can I order HemoHIM?", answer: "Send us a message on WhatsApp. We will confirm availability, current pricing, payment options and delivery terms." }, { question: "Can I use HemoHIM if I have a medical condition?", answer: "If you have a medical condition, are pregnant or breastfeeding, have allergies, or take medication, consult a qualified healthcare professional before use." }] },
  contacts: { label: "Contact us", title: "We are here to help", description: "WhatsApp is the fastest way to reach us. Contact us for availability, ordering, registration support and delivery options.", whatsapp: "+7 708 271 7008", email: "hemohim.atomy.ru@gmail.com", instagram: "hemohim.atomy.ru", tiktok: "hemohim.atomy.ru", facebook: "hemohim.atomy.ru@gmail.com" },
  footer: { infoTitle: "Information", productLinks: "Product", contactLinks: "Contact" },
  disclaimer: "This website is for informational purposes only. HemoHIM is a dietary supplement, not a medicine. If you have a medical condition, are pregnant or breastfeeding, have allergies, or take medication, consult a qualified healthcare professional before use."
};