export const uz = {
  locale: "uz",
  siteName: "Atomy HemoHIM",
  whatsapp: "+7 708 271 7008",
  whatsappLink: "https://wa.me/77082717008",
  nav: { product: "Mahsulot haqida", ingredients: "Tarkibi", benefits: "Afzalliklari", atomy: "Atomy", catalog: "Katalog", registration: "Ro‘yxatdan o‘tish", reviews: "Sharhlar", order: "Buyurtma", faq: "Savollar" },
  common: { koreanProduct: "Atomy kompaniyasining koreys mahsuloti", productLabel: "Mahsulot haqida", ingredientsLabel: "Tarkibi", benefitsLabel: "Afzalliklari", videoLabel: "Video", galleryLabel: "Galereya", formatLabel: "Format", orderLabel: "Buyurtma", contactsLabel: "Aloqa", languageLabel: "Til", consultation: "Maslahat olish", watchVideo: "Videoni ko‘rish" },
  hero: { title: "Atomy HemoHIM", description: "Angelica Gigas, Cnidium Officinale va Paeonia Lactiflora asosidagi puxta ishlab chiqilgan o‘simlik kompleksiga ega premium koreys mahsuloti.", cta: "WhatsApp orqali yozish", secondary: "HemoHIM haqida bilish", imageAlt: "Atomy HemoHIM qadoqlanishi", stats: [{ value: "3", label: "o‘simlik komponenti" }, { value: "20 ml", label: "har bir sasheda" }, { value: "60", label: "har bir qutida" }] },
  productIntro: {
    title: "HemoHIM — natijalari tufayli e’tibor qozongan mahsulot",
    paragraphs: [
      "Nega ayrim odamlar kun oxiriga kelib butunlay holdan toyadi, boshqalari esa yuqori yuklamadan keyin ham tetik qoladi? Umumiy holatga uyqu, ovqatlanish, stress, jismoniy faollik va immun tizimining normal ishlashi kabi ko‘plab omillar ta’sir qiladi.",
      "HemoHIM ko‘p yillardan beri Atomy kompaniyasining eng taniqli mahsulotlaridan biri bo‘lib kelmoqda. Uning o‘simlik kompleksi Koreya Atom Energiyasi Tadqiqot Instituti (KAERI) doirasidagi ko‘p yillik ilmiy loyiha asosida ishlab chiqilgan, mahsulot esa Kolmar BNH tomonidan ishlab chiqariladi.",
      "Kompleks uchta o‘simlik komponentiga asoslangan: gigant dudnik, jgun ildizi va pion. Zamonaviy ekstraksiya va standartlashtirish texnologiyalari HemoHIM asosiga aylangan barqaror o‘simlik tarkibini yaratishga imkon berdi.",
      "Ko‘plab mamlakatlarda HemoHIM faol hayot tarzini olib boradigan odamlar orasida, ayniqsa jismoniy va hissiy yuklama, jadallashgan ish va tez-tez safar davrlarida tanlanadi.",
      "Muhim jihat: HemoHIM dori vositasi emas va kasalliklarni davolash uchun mo‘ljallanmagan. Bu muvozanatli ovqatlanish va sog‘lom turmush tarzining bir qismi sifatida qo‘llanadigan oziq-ovqat qo‘shimchasidir.",
      "HemoHIMning muhim tomonlaridan biri — ishlab chiqishga tizimli yondashuv: ko‘p yillik tadqiqotlar, zamonaviy ishlab chiqarish va sifat nazoratiga e’tibor.",
      "Bozorda har kuni yangi qo‘shimchalar paydo bo‘ladi, biroq ularning faqat ayrimlari yillar davomida xalqaro miqyosda tanilgan bo‘lib qoladi. HemoHIM Atomy kompaniyasining flagman mahsulotlaridan biri bo‘lib qolmoqda."
    ],
    note: "HemoHIM biologik faol qo‘shimcha bo‘lib, dori vositasi emas. Kasallik, homiladorlik yoki emizish davri, allergiya yoki dori qabul qilish holatida foydalanishdan oldin mutaxassis bilan maslahatlashing.",
    imageAlt: "Atomy HemoHIM qulay sashelarda", imageBadge: "Qulay format", imageTitle: "20 ml bir martalik sashelarda", imageText: "Har bir qutida 60 ta sashe"
  },
  ingredients: { title: "Uchta o‘simlik komponenti", text: "HemoHIM maxsus kompleksi puxta tanlangan uchta o‘simlik komponentini birlashtiradi.", items: [{ title: "Gigant dudnik", description: "Koreys angelikasi — HemoHIM kompleksining uchta asosiy komponentidan biri.", imageAlt: "HemoHIM tarkibidagi gigant dudnik" }, { title: "Jgun ildizi", description: "HemoHIM maxsus formulasiga kiritilgan an’anaviy o‘simlik komponenti.", imageAlt: "HemoHIM tarkibidagi jgun ildizi" }, { title: "Yapon pioni", description: "Uch o‘simlikdan iborat muvozanatli formulani yakunlovchi pion.", imageAlt: "HemoHIM tarkibidagi yapon pioni" }] },
  benefits: { title: "Nega HemoHIM tanlanadi", items: [{ title: "Koreyada ishlab chiqilgan", text: "Koreys tadqiqotlari va o‘simlik komponentlari bo‘yicha tajribaga asoslangan mahsulot." }, { title: "Qulay sashelar", text: "Saqlash, o‘zingiz bilan olib yurish va kundalik rejimga qo‘shish oson." }, { title: "Xalqaro tan olinishi", text: "Atomy kompaniyasining xalqaro bozorlardagi eng mashhur mahsulotlaridan biri." }, { title: "Sifatga e’tibor", text: "Atomy tamoyiliga mos: yuqori sifat — oqilona narxda." }] },
  video: { title: "HemoHIM tarixi va ishlab chiqilishi", description: "HemoHIM o‘simlik kompleksining kelib chiqishi, ishlab chiqish yondashuvi va mahsulotning asosiy jihatlari haqida videoni tomosha qiling.", eyebrow: "Mahsulot haqida video", cardTitle: "Nimalarni bilib olasiz", points: ["HemoHIM qanday ishlab chiqilgani", "O‘simlik kompleksi nimalardan iboratligi", "Ishlab chiqish va sifatga qanday yondashilishi"], button: "WhatsApp orqali savol berish", iframeTitle: "Atomy HemoHIM video taqdimoti" },
  gallery: { title: "HemoHIM yaqindan", description: "Mahsulotning rasmiy suratlari: quti, tashqi ko‘rinish va qulay sashe formati.", images: ["Atomy HemoHIM rasmiy surati", "Atomy HemoHIM qadoqlanishi", "Atomy HemoHIM sashelari"], formatTitle: "Kundalik foydalanish uchun qulay bir martalik sashelar", formatText: "Ixcham sashelarni uyda saqlash va o‘zingiz bilan olib yurish qulay. Qadoq hajmi va qo‘llash bo‘yicha ko‘rsatmalar bozorga qarab farq qilishi mumkin — mahalliy qadoqdagi ma’lumotga amal qiling." },
  aboutAtomy: { label: "Atomy", title: "Atomy kompaniyasi haqida", text: "Atomy — 2009-yilda tashkil etilgan Janubiy Koreya kompaniyasi. U sog‘liq, go‘zallik, shaxsiy parvarish, uy va kundalik hayot uchun mahsulotlarni yuqori sifatni oqilona narxda taklif etish tamoyili asosida taqdim etadi." },
  catalog: { label: "Atomy katalogi", title: "Atomy mahsulotlarining to‘liq assortimenti", description: "Katalogda sog‘liq, teri parvarishi, shaxsiy gigiyena, uy va kundalik hayot uchun mahsulotlar jamlangan. Amaldagi assortiment va narxlarni Atomy Kazakhstan rasmiy internet-do‘konida tekshirish qulay.", allProducts: "Barcha mahsulotlarni ko‘rish", printCatalog: "Atomy katalogi 2026", categoriesLabel: "Katalog bo‘limlari", categories: ["Sog‘liq", "Teri parvarishi", "Bolalar uchun", "Erkaklar uchun", "Quyoshdan himoya", "Dekorativ kosmetika", "Soch va tana", "Og‘iz bo‘shlig‘i parvarishi", "Oziq-ovqat mahsulotlari", "Kundalik hayot uchun mahsulotlar"], note: "Narxlar, mavjudlik va assortiment o‘zgarishi mumkin. Buyurtmadan oldin Atomy Kazakhstan rasmiy saytida dolzarb ma’lumotni tekshiring." },
  registration: { label: "Hamkorlik", title: "Atomy tizimida mustaqil ro‘yxatdan o‘tish", description: "Ro‘yxatdan o‘tish Atomy Kazakhstan rasmiy saytida shaxsiy havola orqali amalga oshiriladi. Anketani to‘ldirish yoki jarayon bosqichlarida savol tug‘ilsa, WhatsApp orqali yozing — yordam beramiz.", button: "Ro‘yxatdan o‘tishni boshlash", helpButton: "WhatsApp orqali yordam", steps: ["Rasmiy ro‘yxatdan o‘tish sahifasiga kiring.", "Ma’lumotlaringizni kiriting va Atomy ko‘rsatmalariga amal qiling.", "Yordam kerak bo‘lsa, WhatsApp orqali bog‘laning."] },
  reviews: { label: "Sharhlar", title: "HemoHIM bilan bog‘liq shaxsiy tajribalar", description: "Bu bo‘limda mahsulotni ishlatgan insonlarning shaxsiy taassurotlari va tajribalari jamlangan.", iframeTitle: "HemoHIM haqida video sharh", cardLabel: "Video sharh", cardTitle: "Shaxsiy tajriba", cardText: "HemoHIM bilan tanishgan insonning o‘z tajribasi haqidagi hikoyasini tomosha qiling. Bunday hikoyalar mahsulotni foydalanuvchi nuqtai nazaridan ko‘rishga yordam beradi, biroq tibbiy maslahat o‘rnini bosmaydi va boshqalarda aynan shunday natija bo‘lishini kafolatlamaydi.", disclaimer: "Natijalar va his-tuyg‘ular har bir insonda turlicha. Ushbu sharh tibbiy tavsiya yoki davolovchi ta’sir isboti emas." },
  order: { title: "HemoHIM qanday buyurtma qilinadi", steps: ["WhatsApp orqali yozing.", "Mavjudligi, amaldagi narxi va yetkazib berish variantlarini aniqlashtiring.", "Mahsulot haqida tushunarli ma’lumot va savollaringizga javob oling.", "Buyurtmani sizga qulay usulda rasmiylashtiring."], cta: "WhatsApp orqali buyurtma berish" },
  faq: { title: "Ko‘p beriladigan savollar", items: [{ question: "HemoHIM nima?", answer: "HemoHIM — gigant dudnik, jgun ildizi va pion kompleksiga asoslangan Atomy o‘simlik mahsuloti." }, { question: "HemoHIM dori vositasimi?", answer: "Yo‘q. HemoHIM dori vositasi emas. Saytdagi ma’lumot umumiy tanishtirish maqsadida taqdim etilgan." }, { question: "HemoHIM qanday buyurtma qilinadi?", answer: "WhatsApp orqali yozing. Biz mavjudligi, amaldagi narxi, to‘lov usullari va yetkazib berish shartlarini aniqlashtiramiz." }, { question: "Kasallik bo‘lsa, foydalanish mumkinmi?", answer: "Kasallik, homiladorlik yoki emizish davri, allergiya yoki dori qabul qilish holatida avval malakali mutaxassis bilan maslahatlashing." }] },
  contacts: { label: "Aloqa", title: "Biz bilan bog‘laning", description: "WhatsApp — biz bilan bog‘lanishning eng tezkor usuli. Mavjudlik, buyurtma, ro‘yxatdan o‘tish va yetkazib berish bo‘yicha yozing.", whatsapp: "+7 708 271 7008", email: "hemohim.atomy.ru@gmail.com", instagram: "hemohim.atomy.ru", tiktok: "hemohim.atomy.ru", facebook: "hemohim.atomy.ru@gmail.com" },
  footer: { infoTitle: "Ma’lumot", productLinks: "Mahsulot", contactLinks: "Aloqa" },
  disclaimer: "Sayt axborot maqsadida yaratilgan. HemoHIM biologik faol qo‘shimcha bo‘lib, dori vositasi emas. Kasallik, homiladorlik yoki emizish davri, allergiya yoki dori qabul qilish holatida foydalanishdan oldin mutaxassis bilan maslahatlashing."
};